### ISSUE TITLE
Can i use UTF-8 codes somehow?

### ISSUE THREAD

**Issue by ShDis** [strumswell/ServerlistMOTD-X#19]
For instance
![scr](https://user-images.githubusercontent.com/71232121/99147010-aaf40200-2696-11eb-9af5-42f3b98ed7e7.jpg)
> RandomMotd:
>   Enable: true
>   Regulars:
>     - '&b%player% &d\u043e\u043f\u044f\u0442\u044c \u0437\u0430\u0431\u043b\u0443\u0434\u0438\u043b\u0441\u044f \u0432 %line%\u043a\u0430\u043d\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u0438&r'

But in servers.properties it works fine
![scr2](https://user-images.githubusercontent.com/71232121/99147278-1c34b480-2699-11eb-9c76-fdeabe6cca5f.jpg)

**Comment by strumswell** [comment]
Hey there, this is a known behaviour. I might add support for this kind of unicode notation in the future. But in the meantime: Have you tried using the cyrillic letters directly instead of using the unicode representation in the config.yml? For me at least, I can use cyrillic letters directly in the config. 

For example:
```
Regulars:
- '&bсобака'
```

**Comment by ShDis** [comment]
Yep, i've tried using cyrillic directly at first. Tried again after updating Protocol Lib and Paper - still looks like this 
![scr3](https://user-images.githubusercontent.com/71232121/99150269-b2bea100-26ac-11eb-8898-57259da14a15.jpg)

**Comment by strumswell** [comment]
I might have found a very easy quick fix you could try: Instead of wrapping the motd texts in a single quote ' try wrapping them in a double quote " everywhere you use the unicode representation of the cyrillic letters. This allows the correct escaping with \u.

So instead of: 
```
RandomMotd:
  Enable: true
  Regulars:
  - '&b%player% &d\u043e\u043f\u044f\u0442\u044c \u0437\u0430\u0431\u043b\u0443\u0434\u0438\u043b\u0441\u044f \u0432 %line%\u043a\u0430\u043d\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u0438&r'
```
<img width="613" alt="Bildschirmfoto 2020-11-14 um 16 46 47" src="https://user-images.githubusercontent.com/6720421/99151130-54d48e00-2699-11eb-84fb-4355f7aae209.png">

Do this:
```
RandomMotd:
  Enable: true
  Regulars:
  - "&b%player% &d\u043e\u043f\u044f\u0442\u044c \u0437\u0430\u0431\u043b\u0443\u0434\u0438\u043b\u0441\u044f \u0432 %line%\u043a\u0430\u043d\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u0438&r"
```
<img width="611" alt="Bildschirmfoto 2020-11-14 um 16 47 12" src="https://user-images.githubusercontent.com/6720421/99151132-5736e800-2699-11eb-9d93-fd6af6d3da9c.png">

Let me know if this helped.
